import { Context } from 'telegraf';
import { Cashfree } from 'cashfree-pg'; // Cashfree SDK
import material from '../../data/material.json'; 
import { saveToFirebase } from './utils/saveToFirebase';
import { db } from './utils/firebase';
import { get, ref, set } from 'firebase/database';

// Initialize Cashfree SDK
Cashfree.XEnvironment = process.env.CASHFREE_ENV === 'production' ? Cashfree.Environment.PRODUCTION : Cashfree.Environment.SANDBOX;
const cashfree = new Cashfree({
  clientId: process.env.CASHFREE_CLIENT_ID!,
  clientSecret: process.env.CASHFREE_CLIENT_SECRET!,
});

interface MaterialItem {
  title: string;
  label: string;
  key: string;
  telegramLink: string;
  productId: string; // Unique ID for payment
}

interface UserData {
  id: string;
  name: string;
  username: string;
  phone?: string;
  email?: string;
  paymentStatus?: { [productId: string]: boolean };
}

let materialData: MaterialItem[] = [];

// Initialize material data with Telegram links
async function initializeMaterialData(): Promise<void> {
  const output: MaterialItem[] = [];
  for (const cat of material) {
    for (const item of cat.items) {
      const tgLink = `https://t.me/Material_eduhubkmrbot?start=${item.key}`;
      output.push({
        title: cat.title,
        label: item.label,
        key: item.key,
        telegramLink: tgLink,
        productId: `prod_${item.key}_${Date.now()}`, // Unique product ID
      });
    }
  }
  materialData = output;
}
initializeMaterialData().catch(console.error);

// Check if user has paid for a specific product
async function checkPaymentStatus(userId: string, productId: string): Promise<boolean> {
  const userRef = ref(db, `users/${userId}`);
  const snapshot = await get(userRef);
  if (snapshot.exists()) {
    const userData = snapshot.val() as UserData;
    return userData.paymentStatus?.[productId] === true;
  }
  return false;
}

// Save payment status to Firebase
async function savePaymentStatus(userId: string, productId: string): Promise<void> {
  const userRef = ref(db, `users/${userId}/paymentStatus`);
  await set(ref(db, `users/${userId}/paymentStatus/${productId}`), true);
}

// Search for materials and rank them
function rankedMatches(query: string): MaterialItem[] {
  const queryWords = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  const results: { item: MaterialItem; rank: number }[] = [];

  for (const item of materialData) {
    const fullText = `${item.title} ${item.label}`.toLowerCase();
    const fullWords = new Set(fullText.split(/\s+/));
    const matchedWords = queryWords.filter((word) => fullWords.has(word));
    const rank = Math.round((matchedWords.length / queryWords.length) * 100);
    if (rank > 0) {
      results.push({ item, rank });
    }
  }

  return results.sort((a, b) => b.rank - a.rank).map((r) => r.item);
}

// Create a Telegraph page with results (for unpaid users)
async function createTelegraphPageForMatches(query: string, matches: MaterialItem[], userId: string): Promise<string> {
  const accessToken = process.env.TELEGRAPH_ACCESS_TOKEN || (await createTelegraphAccount());
  const content = [
    { tag: 'h3', children: [`Results for: "${query}"`] },
    { tag: 'p', children: [`Found ${matches.length} study materials:`] },
    {
      tag: 'ul',
      children: await Promise.all(
        matches.map(async (item) => {
          const isPaid = await checkPaymentStatus(userId, item.productId);
          const link = isPaid ? item.telegramLink : `${process.env.NEXT_PUBLIC_BASE_URL}/pay?productId=${item.productId}&userId=${userId}`;
          return {
            tag: 'li',
            children: [
              '• ',
              { tag: 'a', attrs: { href: link, target: '_blank' }, children: [item.label] },
              ` (${item.title})`,
            ],
          };
        })
      ),
    },
    { tag: 'hr' },
    { tag: 'h4', children: ['ℹ️ Resources & Instructions'] },
    ...defaultInstructions,
    { tag: 'p', attrs: { style: 'color: gray; font-size: 0.8em' }, children: ['Generated by Study Bot'] },
  ];

  const res = await fetch('https://api.telegra.ph/createPage', {
    method: 'POST',
    body: new URLSearchParams({
      access_token: accessToken,
      title: `Study Material: ${query.slice(0, 50)}`,
      author_name: 'Study Bot',
      content: JSON.stringify(content),
      return_content: 'true',
    }),
  });

  const data = await res.json();
  if (data.ok) return `https://telegra.ph/${data.result.path}`;
  throw new Error(data.error);
}

// Telegraph account creation
async function createTelegraphAccount(): Promise<string> {
  const res = await fetch('https://api.telegra.ph/createAccount', {
    method: 'POST',
    body: new URLSearchParams({ short_name: 'studybot', author_name: 'Study Bot' }),
  });
  const data = await res.json();
  if (data.ok) return data.result.access_token;
  throw new Error(data.error);
}

// Default Telegraph instructions
const defaultInstructions = [
  {
    tag: 'p',
    children: [
      '📺 How to open link: ',
      {
        tag: 'a',
        attrs: { href: 'https://youtu.be/S912R5lMShI?si=l5RsBbkbXaxFowbZ' },
        children: ['YouTube Guide'],
      },
    ],
  },
  {
    tag: 'p',
    children: ['📚 Join more recommended bots:'],
  },
  {
    tag: 'ul',
    children: [
      {
        tag: 'li',
        children: [
          { tag: 'a', attrs: { href: 'https://t.me/Material_eduhubkmrbot' }, children: ['@Material_eduhubkmrbot'] },
          ' - Study materials',
        ],
      },
      {
        tag: 'li',
        children: [
          { tag: 'a', attrs: { href: 'https://t.me/EduhubKMR_bot' }, children: ['@EduhubKMR_bot'] },
          ' - QuizBot',
        ],
      },
      {
        tag: 'li',
        children: [
          { tag: 'a', attrs: { href: 'https://t.me/NEETPW01' }, children: ['@NEETPW01'] },
          ' - Group For Discussion',
        ],
      },
      {
        tag: 'li',
        children: [
          { tag: 'a', attrs: { href: 'https://t.me/NEETUG_26' }, children: ['@NEETUG_26'] },
          ' - NEET JEE Channel',
        ],
      },
    ],
  },
];

// Bot handler
export function cashStudySearch() {
  return async (ctx: Context) => {
    try {
      if (!ctx.message || !('text' in ctx.message)) return;
      const query = ctx.message.text.trim();
      if (!query) {
        await ctx.reply('❌ Please enter a search term.', { reply_to_message_id: ctx.message.message_id });
        return;
      }

      // Extract user details from Telegram
      const user = ctx.from;
      if (!user) {
        await ctx.reply('❌ Unable to fetch user details.', { reply_to_message_id: ctx.message.message_id });
        return;
      }

      const userId = String(user.id);
      const userData: UserData = {
        id: userId,
        name: user.first_name || '',
        username: user.username || '',
      };

      // Save user to Firebase
      await saveToFirebase(user);

      // Check if user has provided phone and email (prompt if missing)
      const userRef = ref(db, `users/${userId}`);
      const snapshot = await get(userRef);
      let userDetails = snapshot.exists() ? snapshot.val() : userData;

      if (!userDetails.phone || !userDetails.email) {
        await ctx.reply(
          '📋 Please provide your phone number and email to proceed with payments. Reply with: /setcontact <phone> <email>',
          { reply_to_message_id: ctx.message.message_id }
        );
        return;
      }

      // Search for materials
      const matches = rankedMatches(query);
      if (matches.length === 0) {
        const mention = ctx.chat?.type?.includes('group') && user.username ? `@${user.username}` : user.first_name || '';
        await ctx.reply(`❌ ${mention}, no materials found for "${query}".`, {
          reply_to_message_id: ctx.message.message_id,
        });
        return;
      }

      // Create Telegraph page with conditional links (direct for paid, payment link for unpaid)
      const telegraphURL = await createTelegraphPageForMatches(query, matches, userId);
      const shortQuery = query.split(/\s+/).slice(0, 3).join(' ');
      const mention = ctx.chat?.type?.includes('group') && user.username ? `@${user.username}` : user.first_name || '';

      await ctx.reply(
        `🔍 ${mention}, found *${matches.length}* matches for *${shortQuery}*:\n[View materials](${telegraphURL})`,
        {
          parse_mode: 'Markdown',
          disable_web_page_preview: true,
          reply_to_message_id: ctx.message.message_id,
        }
      );
    } catch (err) {
      console.error(err);
      await ctx.reply('❌ Something went wrong. Please try again later.', {
        reply_to_message_id: ctx.message?.message_id,
      });
    }
  };
}

// Handle contact setting command
export function setContact() {
  return async (ctx: Context) => {
    try {
      if (!ctx.message || !('text' in ctx.message)) return;
      const args = ctx.message.text.split(' ').slice(1);
      if (args.length < 2) {
        await ctx.reply('❌ Usage: /setcontact <phone> <email>', { reply_to_message_id: ctx.message.message_id });
        return;
      }

      const [phone, email] = args;
      const userId = String(ctx.from?.id);
      if (!userId) {
        await ctx.reply('❌ Unable to fetch user details.', { reply_to_message_id: ctx.message.message_id });
        return;
      }

      // Validate phone and email (basic validation)
      const phoneRegex = /^\+?[1-9]\d{1,14}$/;
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!phoneRegex.test(phone) || !emailRegex.test(email)) {
        await ctx.reply('❌ Invalid phone or email format.', { reply_to_message_id: ctx.message.message_id });
        return;
      }

      // Save contact details to Firebase
      await set(ref(db, `users/${userId}`), {
        ...ctx.from,
        phone,
        email,
        savedAt: new Date().toISOString(),
      });

      await ctx.reply('✅ Contact details saved successfully!', { reply_to_message_id: ctx.message.message_id });
    } catch (err) {
      console.error(err);
      await ctx.reply('❌ Failed to save contact details.', { reply_to_message_id: ctx.message.message_id });
    }
  };
}

// Webhook handler for Cashfree payment confirmation
export async function handleWebhook(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: 'Method Not Allowed' });
  }

  try {
    const webhookData = req.body;
    const orderId = webhookData.order_id;
    const paymentStatus = webhookData.payment_status;

    if (paymentStatus === 'SUCCESS') {
      // Fetch order details to get userId and productId
      const order = await Cashfree.PGOrderFetch({
        orderId,
      });

      const userId = order.customer_details.customer_id; // Assuming userId was set as customer_id
      const productId = order.order_meta.product_id; // Assuming productId was stored in order_meta

      // Update payment status in Firebase
      await savePaymentStatus(userId, productId);

      // Notify user via Telegram (if bot is integrated with Telegram)
      // This requires a Telegram bot instance to send messages
      // Example: bot.telegram.sendMessage(userId, `✅ Payment successful for ${productId}! You can now access the material.`);
    }

    return res.status(200).json({ success: true });
  } catch (error) {
    console.error('Webhook processing failed:', error);
    return res.status(500).json({ success: false, error: 'Webhook processing failed' });
  }
}
